openapi: "3.0.3"
info:
  title: "digidatesAPI"
  description: "API for time and date functions"
  version: "1.0"
  contact:
    email: "webmaster@digidates.de"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
servers:
  - url: "https:/api.digidates.de/{basePath}"
    description: "API Server"
    variables:
      basePath:
        default: v1
paths:
  /unixtime:
    get:
      description: Returns unix time
      responses:
        '200':
          description: A unix time
          content:
            application/json:
              schema:
                type: int
      parameters:
      - in: "body"
        name: "timestamp"
        description: "Timestamp to convert"
        required: false
        schema:
          type: string
          example: "1970-01-01 00:00:01"
  /week:
    get:
      description: Returns week number
      responses:
        '200':
          description: Number of Week
          content:
            application/json:
              schema:
                type: int
      parameters:
      - in: "body"
        name: "timestamp"
        description: "Time to get week of"
        required: false
        schema:
          type: string
          example: "1970-01-01 00:00:01"
  /leapyear:
    get:
      description: Leap year or not
      responses:
        '200':
          description: Is leap year or not
          content:
            application/json:
              schema:
                type: boolean
      parameters:
        - in: "body"
          name: "timestamp"
          description: "Time to check if in leap year or not"
          required: false
          schema:
            type: string
            example: "1970-01-01 00:00:01"
  /checkdate:
    get:
      description: Valid date or not
      responses:
        '200':
          description: Is it a valid date or not
          content:
            application/json:
              schema:
                type: boolean
      parameters:
        - in: "body"
          name: date
          description: "Date to check if valid"
          required: true
          schema:
            type: string
            example: "2020-01-01"
  /weekday:
    get:
      description: Get the weekday
      responses:
        '200':
          description: Get the weekday
          content:
            application/json:
              schema:
                type: integer
      parameters:
        - in: "body"
          name: date
          description: "Date of which to get week day"
          required: false
          schema:
            type: integer
            example: "2020-01-01"
