openapi: "3.0.3"
info:
  title: "digidatesAPI"
  description: "API for time and date functions"
  version: "1.0"
  contact:
    email: "webmaster@digidates.de"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
servers:
  - url: "https:/digidates.de/api/{basePath}"
    description: "Live Server"
    variables:
      basePath:
        default: v1
paths:
  /unixtime:
    get:
      description: Returns unix time
      responses:
        '200':
          description: A unix time
          content:
            application/json:
              schema:
                type: integer
      parameters:
        - in: "query"
          name: "timestamp"
          description: "Timestamp to convert"
          schema:
            type: string
            example: "1970-01-01 00:00:01"
  /week:
    get:
      description: Returns week number
      responses:
        '200':
          description: Number of Week
          content:
            application/json:
              schema:
                type: integer
      parameters:
        - in: "query"
          name: "timestamp"
          description: "Time to get week of"
          schema:
            type: string
            example: "1970-01-01 00:00:01"
  /leapyear:
    get:
      description: Leap year or not
      responses:
        '200':
          description: Is leap year or not
          content:
            application/json:
              schema:
                type: boolean
      parameters:
        - in: "query"
          name: "timestamp"
          description: "Time to check if in leap year or not"
          schema:
            type: string
            example: "1970-01-01 00:00:01"
  /checkdate:
    get:
      description: Valid date or not
      responses:
        '200':
          description: Is it a valid date or not
          content:
            application/json:
              schema:
                type: boolean
      parameters:
        - in: "query"
          name: date
          description: "Date to check if valid"
          schema:
            type: string
            example: "2020-01-01"
  /weekday:
    get:
      description: Get the weekday
      responses:
        '200':
          description: Get the weekday
          content:
            application/json:
              schema:
                type: integer
      parameters:
        - in: "query"
          name: date
          description: "Date of which to get week day"
          schema:
            type: integer
            example: "2020-01-01"
  /progress:
    get:
      description: Progress made from one timestamp to another
      responses:
        '200':
          description: Get the progress
          content:
            application/json:
              schema:
                type: object
                properties:
                  float:
                    type: number
                  percent:
                    type: integer
      parameters:
        - in: "query"
          name: start
          description: Timestamp for start of period
          schema:
            type: string
            example: "2022-01-01"
        - in: "query"
          name: end
          description: Timestamp for end of period
          schema:
            type: string
            example: "2022-12-31"
  /age/{date}:
    get:
      description: Age of give date
      responses:
        '200':
          description: Get the age
          content:
            application/json:
              schema:
                type: object
                properties:
                  age:
                    type: integer
                  ageextended:
                    type: object
                    properties:
                      years:
                        type: integer
                      months:
                        type: integer
                      days:
                        type: integer
      parameters:
        - in: "path"
          name: date
          required: true
          description: Date of Birthday
          schema:
            type: string
            example: "1970-01-01"